### ISSUE TITLE
Build failure on Windows Vista 32 bit, Strawberry Perl 5.12

### ISSUE THREAD

**Issue by run4flat** [dk/PDL-Drawing-Prima#26]
For a Windows Vista 32 bit machine running strawberry 5.12, this is what happens with "cpan PDL::Graphics::Prima": https://gist.github.com/3062942

**Comment by mohawk2** [comment]
Conceivably this could have been PDL-generated `BOOT` code which needs to load PDL::Core in order to get at `$PDL::SHARE` which has the `PDL` pointer which has all the "core" PDL C functions. These days it does `perl_require_pv("PDL/Core.pm")` (which works correctly) but some buggy code from ages ago might have done the equivalent of `perl_require_pv("PDL::Core")` which would a) not work; and b) show the symptoms described here.

I'd suggest this issue be closed as unfixable.

**Comment by dk** [comment]
Is this actual still? I've brushed up the P::D::P so it compiles and runs all tests fine now.

**Comment by mohawk2** [comment]
@dk I think that's up to you now!

**Comment by dk** [comment]
Sure can do but usually it is a good style if you throw a pull request in you also drive it through until it is merged. But nevermind I'll take over
